

const { basename } = require("path");
const {
  sources: { RawSource },
  Compilation,
} = require("webpack");

class AssetsSnippetPlugin {
  constructor(config) {
    this.config = {
      manifestFileName: config.manifestFileName || "assets/__manifest",
    };
  }

  static emitAsset(compilation, assetName, assetSource) {
    try {
      const asset = compilation.getAsset(assetName);
      if (asset) {
        compilation.updateAsset(assetName, assetSource, { immutable: true });
      } else {
        compilation.emitAsset(assetName, assetSource, { immutable: true });
      }
    } catch (error) {
      compilation.errors.push(error);
      throw error;
    }
  }
  /** @param {import("webpack").Compiler} [compiler] */
  apply(compiler) {
    if (!compiler) return;

    compiler.hooks.thisCompilation.tap(
      AssetsSnippetPlugin.name,
      (compilation) => {
        compilation.hooks.processAssets.tap(
          {
            name: AssetsSnippetPlugin.name,
            stage: Compilation.PROCESS_ASSETS_STAGE_ADDITIONS,
          },
          () => {
            const asset = compilation.getAsset("snippets/theme_assets.liquid");
            if (asset) {
              const { chunks } = compilation.getStats().toJson({
                all: false,
                assets: true,
                chunks: true,
              });

              const assetsSnippetContents = this.buildThemeInitSnippet(chunks);
              compilation.updateAsset(
                asset.name,
                new RawSource(assetsSnippetContents),
              );
            }
          },
        );

        // Create manifest file
        if (compiler.options.mode === "production") {
          const {
            outputOptions: {
              hashDigest,
              hashDigestLength,
              hashFunction,
              hashSalt,
            },
          } = compilation;
          const buildOutputMap = {};

          compilation.hooks.processAssets.tap(
            {
              name: AssetsSnippetPlugin.name,
              stage: Compilation.PROCESS_ASSETS_STAGE_REPORT,
              additionalAssets: true,
            },
            (assets) => {
              const isTemplate = /^templates.*\.json$/;

              for (const [name, source] of Object.entries(assets)) {
                // TODO: Get ingored files from config.yml
                // Do not hash `.json` templates
                if (
                  name === this.config.manifestFileName ||
                  isTemplate.test(name)
                )
                  continue;

                const hash = compiler.webpack.util.createHash(
                  /** @type {string} */ (hashFunction),
                );
                if (hashSalt) hash.update(hashSalt);
                buildOutputMap[name] = hash
                  .update(source.buffer())
                  .digest(hashDigest)
                  .toString()
                  .slice(0, hashDigestLength);
              }

              AssetsSnippetPlugin.emitAsset(
                compilation,
                this.config.manifestFileName,
                new RawSource(JSON.stringify(buildOutputMap)),
              );
            },
          );
        }
      },
    );
  }

  buildThemeInitSnippet = (chunks) => {
    const files = chunks
      .flatMap((chunk) => chunk.files)
      .map((file) => {
        const fileName = basename(file);
        return [file, `?{{ '${fileName}' | asset_url | split: '?' | last }}`];
      });

    return `
{% # theme-check-disable %}
{% comment %}
  IMPORTANT:
  This snippet is automatically generated by Webpack.
  Do not attempt to modify this file directly, as any changes will be overwritten by the next build.

  Accepts:
  - card_collection: {String} Theme asset file name
  - preload: {Boolean} Preload the asset (optional)
  - is_module: {Boolean} Denote whether the script is a module (optional)

  Usage:
  {%- render 'theme_assets', import_map: true -%}
  {%- render 'theme_assets' with 'main.min.js' -%}
  {%- render 'theme_assets' with 'main.min.css' -%}
  {%- render 'theme_assets' with 'section-product.min.css' -%}
  {%- render 'theme_assets' with 'section-product.min.css', preload: true -%}
{%- endcomment -%}

{% assign asset_name = theme_assets %}

{% if asset_name %}

  {% if asset_name contains '.css' %}
    {{ asset_name | asset_url | stylesheet_tag: preload: preload }}
  {% endif %}

  {% if asset_name contains '.js' %}
    {% liquid
      assign use_module = is_module | default: false
      if use_module
        assign use_module = 'module'
      else
        assign use_module = ''
      endif
    %}
    {% if preload %}
      <link rel="{{ use_module }}preload" href="{{ asset_name | asset_url }}" as="script">
    {% endif %}
    <script src="{{ asset_name | asset_url }}" type="{{ use_module }}" defer></script>
  {% endif %}

{% elsif import_map == true %}

  <script type="application/json" data-public-path="{{ 'filename.js' | asset_url | split: '/assets/filename.js' | first }}/">${JSON.stringify(
    Object.fromEntries(files),
  )}</script>

{% endif %}
`;
  };
}

module.exports = AssetsSnippetPlugin;
